### ISSUE TITLE
linux mint repo ignored 

### ISSUE THREAD

**Issue by youngunix** [volitank/nala#23]
Is there a reason why nala ignores Linux Mint's repos?

**Comment by volitank** [comment]
What do you mean by it ignoring Mint Repos?

**Comment by youngunix** [comment]
When I run `nala update`, I get (ubuntu & debian repos are fine) `Ignored: http://packages.linuxmint.com/ victoria InRelease`.

**Comment by volitank** [comment]
Oh I see. If Nala is showing this when you do `apt update` You should see a very similar message of IGN instead of Ignored.

In this case it means that apt tried to get the InRelease file from LinuxMint Victoria, but it could not be found. Apt will then probably fallback to the Release file which Linux Mint does have in their repo.

http://packages.linuxmint.com/dists/victoria/

IGN is not really too much of concern. If apt is unable to find anything it will Error instead.

**Comment by youngunix** [comment]
Thanks for the hint. 

I commented all the lines in the official source list, chose a different mirror, and added the repo to the nala' source list and ran `nala update`, but this time around, I got both the `ignored` and `no change` right below it for the victoria repo! Is this an intended output? If not, are there any other troubleshooting steps I can try?

**Comment by youngunix** [comment]
Running `nala clean --lists` didn't make a difference, so I chose a different mirror. However, now it is ignoring only the one that has `InRelease` and pulls from the `Release`. What is the difference between the two? And will I be missing updates from the Linux Mint repo for LM specific packages?

**Comment by volitank** [comment]
Yes every mirror for Mint is going to do this since they are all the same. There isn't too much difference between InRelease and Release, just different styles. InRelease file is clear signed, while Release has a Release.gpg key along with it for verification. Both Repository methods are safe, and will function no different for you. You will get updates just fine.

To be clear, this issue is a Linux Mint issue with their repositories. They are just doing it a little different than Debian, Ubuntu, etc. It is perfectly safe and will function no different. You will just get that InRelease was ignored as it doesn't exist.

**Comment by youngunix** [comment]
Thank you for the detailed explanation. I confirmed your recommendations and I believe this issue is resolved.
