### ISSUE TITLE
Nala should accept 'y' (as well as 'j') in German Locale

### ISSUE THREAD

**Issue by leogott** [volitank/nala#46]
Few Linux command line tools translate their output according to locale. But when those with a German translation interactively ask for a [J/n]  ( think [Y/n] ) confirmation, they also accept a 'y'.

I've come to expect that and would like nala to behave that way.

Version 0.11.1

**Comment by volitank** [comment]
This has been fixed since version 0.11.1, I would suggest updating.

The install instructions contains the command that can set it up for you https://gitlab.com/volian/nala/-/wikis/Installation

0.11.1 sounds like it's possible you installed `nala-legacy`, if that is the case I would `apt purge nala-legacy` prior to running that as I think it would cause it to fail.

There is also a way to install a standalone binary that won't install python system libraries, but you have to do that from source at the moment.
