### ISSUE TITLE
--reinstall Option not Working with nala

### ISSUE THREAD

**Issue by faxotherapy** [volitank/nala#48]
I naively thought that `sudo nala install bat --reinstall` would work. I guess I should not use _nala_ when using `--reinstall` flag? Thank you for your help.

**Comment by volitank** [comment]
Yes, for now this option cannot be used or implemented. The python-apt library Nala uses to interact with apt does not have this functionality from what I could tell. At least the last time I looked into implementing it.

Nala is currently under the process of being rewritten in rust though, and when it is complete it will have this functionality as I also had to write https://gitlab.com/volian/rust-apt in order to get started.
